name: Build custom caddy
on: [push, workflow_dispatch]
jobs:
  xcaddy-with-cloudflare:
    name: Build xcaddy with cloudflare ddns
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v4

      - run: go env GOPATH

      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - run: xcaddy build --with github.com/caddy-dns/cloudflare --with github.com/WeidiDeng/caddy-cloudflare-ip

      - run: echo "CADDY_VERSION=$(./caddy version)" | tee -a "$GITHUB_ENV"

      - run: echo "CADDY_SHORTVER=$(echo $CADDY_VERSION | cut -f 1 -d ' ')" | tee -a "$GITHUB_ENV"

      - uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: caddy
          name: ${{ env.CADDY_SHORTVER }}
          append_body: true
          body: "built version: ${{ env.CADDY_VERSION }}"
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
